#!/usr/bin/env python
from shet.server import ShetServerFactory
from twisted.internet import reactor


def main():
	port = 11235

	reactor.listenTCP(port, ShetServerFactory())
	print "Running on port %i..." % port
	reactor.run()


if __name__ == "__main__":
	main()
